const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
async function api(path,opts={}){const r=await fetch(path,{credentials:'same-origin',headers:{'content-type':'application/json',...(opts.headers||{})},...opts});const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d.error||`Request failed (${r.status})`),{status:r.status});return d}
async function boot(){try{await api('/api/admin/session');$('[data-ops]').hidden=false;$('[data-login]').hidden=true;await Promise.all([loadSettings(),loadIntegration(),loadLeads()])}catch(e){$('[data-login]').hidden=false;$('[data-ops]').hidden=true}}
async function loadSettings(){const {settings}=await api('/api/admin/settings');$('[data-whatsapp]').value=settings.whatsapp_number||'';$('[data-show-qty]').checked=settings.show_public_quantity==='1'}
$('[data-save-settings]').addEventListener('click',async()=>{const st=$('[data-settings-status]');st.textContent='Saving…';try{await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({whatsapp_number:$('[data-whatsapp]').value,show_public_quantity:$('[data-show-qty]').checked})});st.textContent='Saved.'}catch(e){st.textContent=e.message}});
async function loadIntegration(){const data=await api('/api/admin/mototrack');const box=$('[data-mappings]');box.replaceChildren();for(const m of data.models){const row=document.createElement('div');row.className='mapping-row';row.dataset.slug=m.slug;const name=document.createElement('div');name.innerHTML=`<strong>${escapeHtml(m.name)}</strong><small>${m.availability}${m.public_quantity==null?'':` · qty ${m.public_quantity}`}</small>`;const input=document.createElement('input');input.value=m.external_key||m.slug;input.maxLength=160;input.dataset.externalKey='';const check=document.createElement('input');check.type='checkbox';check.checked=m.enabled!==false;check.dataset.enabled='';row.append(name,input,check);box.append(row)}const s=$('[data-sync-state]');s.textContent=data.configured?(data.last_sync?`Configured · last ${data.last_sync.status} sync: ${data.last_sync.records_updated}/${data.last_sync.records_seen} records · ${data.last_sync.created_at}`:'Configured · no sync has run yet'):'MOTOTRACK_URL is not configured yet. Save the secret/URL in Cloudflare before syncing.'}
$('[data-save-mappings]').addEventListener('click',async()=>{const st=$('[data-sync-status]');st.textContent='Saving mappings…';try{const models=$$('.mapping-row').map(r=>({slug:r.dataset.slug,external_key:r.querySelector('[data-external-key]').value,enabled:r.querySelector('[data-enabled]').checked}));await api('/api/admin/mototrack',{method:'PUT',body:JSON.stringify({models})});st.textContent='Mappings saved.';await loadIntegration()}catch(e){st.textContent=e.message}});
$('[data-sync]').addEventListener('click',async()=>{const st=$('[data-sync-status]');st.textContent='Syncing…';try{const r=await api('/api/admin/mototrack/sync',{method:'POST',body:'{}'});st.textContent=`Sync complete: ${r.records_updated}/${r.records_seen} public records updated.`;await loadIntegration()}catch(e){st.textContent=e.message}});
async function loadLeads(){const status=$('[data-lead-filter]').value;const {leads}=await api(`/api/admin/leads?limit=200${status?`&status=${encodeURIComponent(status)}`:''}`);const list=$('[data-leads]');list.replaceChildren();if(!leads.length){list.textContent='No inquiries in this view.';return}for(const l of leads)list.append(leadCard(l))}
function leadCard(l){const c=document.createElement('article');c.className='lead-card';const who=document.createElement('div');who.innerHTML=`<span class="lead-badge">${escapeHtml(l.status)}</span><h3>${escapeHtml(l.name)}</h3><p>${escapeHtml(l.city||'')}</p>`;const contact=document.createElement('div');const phone=String(l.phone||'').replace(/\D/g,'');contact.innerHTML=`<p><a href="tel:${escapeHtml(phone)}">${escapeHtml(l.phone)}</a></p>${l.email?`<p><a href="mailto:${escapeHtml(l.email)}">${escapeHtml(l.email)}</a></p>`:''}<p>${escapeHtml(l.created_at)}</p>`;const msg=document.createElement('div');msg.innerHTML=`<p><strong>${escapeHtml(l.model_slug||'General inquiry')}</strong></p><p>${escapeHtml(l.message||'No message')}</p>`;const select=document.createElement('select');for(const s of ['new','contacted','qualified','closed','spam'])select.add(new Option(s[0].toUpperCase()+s.slice(1),s));select.value=l.status;select.addEventListener('change',async()=>{try{await api(`/api/admin/leads/${l.id}`,{method:'PATCH',body:JSON.stringify({status:select.value})})}catch(e){alert(e.message);select.value=l.status}});c.append(who,contact,msg,select);return c}
$('[data-lead-filter]').addEventListener('change',loadLeads);$('[data-refresh-leads]').addEventListener('click',loadLeads);$('[data-logout]').addEventListener('click',async()=>{try{await api('/api/admin/logout',{method:'POST',body:'{}'})}catch{}location.href='./'});
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
boot();
