CREATE TABLE IF NOT EXISTS site_content (
  key TEXT PRIMARY KEY,
  group_name TEXT NOT NULL,
  label TEXT NOT NULL,
  value_en TEXT NOT NULL DEFAULT '',
  value_fr TEXT NOT NULL DEFAULT '',
  input_type TEXT NOT NULL DEFAULT 'text' CHECK (input_type IN ('text','textarea')),
  sort_order INTEGER NOT NULL DEFAULT 100,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS site_media (
  slot TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  object_key TEXT NOT NULL,
  content_type TEXT NOT NULL,
  alt_en TEXT NOT NULL DEFAULT '',
  alt_fr TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO site_content(key,group_name,label,value_en,value_fr,input_type,sort_order) VALUES
('hero.eyebrow','Homepage · Hero','Eyebrow','Showroom experience · Lubumbashi','Expérience showroom · Lubumbashi','text',10),
('hero.line1','Homepage · Hero','Main headline','Move with','Avancez avec','text',20),
('hero.lead','Homepage · Hero','Hero description','Motorcycles made for everyday work, city movement and the roads of Katanga. Discover our Eagle and Super ranges in Lubumbashi.','Des motos pensées pour le travail quotidien, les déplacements urbains et les routes du Katanga. Découvrez nos gammes Eagle et Super à Lubumbashi.','textarea',30),
('hero.ctaPrimary','Homepage · Hero','Primary button','Explore motorcycles','Découvrir les motos','text',40),
('hero.ctaSecondary','Homepage · Hero','Secondary button','Visit the dealer','Visiter la concession','text',50),
('hero.visualLabel','Homepage · Hero','Photo label','HUANGHE RANGE','GAMME HUANGHE','text',60),
('hero.visualTitle','Homepage · Hero','Photo headline','Built to keep moving.','Conçue pour avancer.','text',70),
('models.kicker','Homepage · Catalogue','Section label','THE RANGE','LA GAMME','text',100),
('models.title','Homepage · Catalogue','Section title','Choose your Huanghe.','Choisissez votre Huanghe.','text',110),
('models.intro','Homepage · Catalogue','Section description','Eagle and Super now have dedicated bilingual product pages, ready for exact dealer photography and confirmed local specifications.','Eagle et Super disposent maintenant de pages produit bilingues dédiées, prêtes à recevoir les photos réelles et les caractéristiques locales confirmées.','textarea',120),
('models.moreTitle','Homepage · Catalogue','More models title','More models can be added as stock arrives.','D’autres modèles pourront être ajoutés selon les arrivages.','text',130),
('models.moreCopy','Homepage · Catalogue','More models description','The catalogue is component-based, so new motorcycles can be added without changing the page structure.','Le catalogue est modulaire : de nouvelles motos peuvent être ajoutées sans modifier la structure de la page.','textarea',140),
('band.tag','Homepage · Heritage','Image label','HUANGHE HERITAGE','HÉRITAGE HUANGHE','text',200),
('band.title','Homepage · Heritage','Image headline','Utility that works as hard as you do.','Une utilité qui travaille aussi dur que vous.','text',210),
('story.kicker','Homepage · Story','Section label','HUANGHE MOTORS','HUANGHE MOTORS','text',300),
('story.title','Homepage · Story','Story title','A motorcycle name with history. A showroom built for Lubumbashi.','Un nom de moto avec une histoire. Un showroom conçu pour Lubumbashi.','text',310),
('story.p1','Homepage · Story','Story paragraph 1','Huanghe traces its motorcycle brand history back decades in China. The Lubumbashi website presents that heritage through the motorcycles actually available from the local dealer.','La marque de motos Huanghe possède plusieurs décennies d’histoire en Chine. Le site de Lubumbashi présente cet héritage à travers les motos réellement proposées par la concession locale.','textarea',320),
('story.p2','Homepage · Story','Story paragraph 2','Dedicated Eagle and Super pages are now live in the site structure. Technical values remain intentionally unpublished until the local dealer confirms the exact variants.','Les pages Eagle et Super sont maintenant intégrées au site. Les données techniques restent volontairement non publiées jusqu’à confirmation des variantes exactes par la concession locale.','textarea',330),
('story.link','Homepage · Story','Dealer link text','Talk to the Lubumbashi dealer','Contacter la concession de Lubumbashi','text',340),
('story.featureLabel','Homepage · Story','Feature label','DESIGNED FOR','PENSÉ POUR','text',350),
('story.featureTitle','Homepage · Story','Feature headline','Real roads. Real work. Real movement.','De vraies routes. Du vrai travail. Du mouvement.','text',360),
('dealer.kicker','Homepage · Dealer CTA','Section label','LUBUMBASHI','LUBUMBASHI','text',400),
('dealer.title','Homepage · Dealer CTA','Section title','See the motorcycles in person.','Venez voir les motos en personne.','text',410),
('dealer.copy','Homepage · Dealer CTA','Description','Contact Huanghe Motors Lubumbashi for current Eagle and Super availability, colours and dealer information.','Contactez Huanghe Motors Lubumbashi pour connaître la disponibilité actuelle des Eagle et Super, les couleurs et les informations de la concession.','textarea',420),
('dealer.visitPage','Homepage · Dealer CTA','Dealer button','Open dealer page','Ouvrir la page concession','text',430),
('dealer.viewEagle','Homepage · Dealer CTA','Eagle button','View Eagle','Voir Eagle','text',440),
('dealer.note','Homepage · Dealer CTA','Dealer note','The dedicated dealer page is live. Exact address, phone, WhatsApp and hours remain unpublished until dealer-confirmed.','La page concession est en ligne. L’adresse exacte, le téléphone, WhatsApp et les horaires restent non publiés jusqu’à confirmation.','textarea',450),
('dealerPage.kicker','Dealership page · Hero','Page label','HUANGHE MOTORS · DR CONGO','HUANGHE MOTORS · RD CONGO','text',500),
('dealerPage.line1','Dealership page · Hero','Main headline','Your Huanghe dealer in','Votre concession Huanghe à','text',510),
('dealerPage.lead','Dealership page · Hero','Hero description','Explore Eagle and Super locally, ask about current availability and get the exact dealer-confirmed motorcycle information before you buy.','Découvrez Eagle et Super localement, demandez la disponibilité actuelle et obtenez les informations exactes confirmées par la concession avant l’achat.','textarea',520),
('dealerPage.contact','Dealership page · Hero','Dealer information button','Dealer information','Informations concession','text',530),
('dealerPage.models','Dealership page · Hero','Motorcycles button','View motorcycles','Voir les motos','text',540),
('dealerPage.visitKicker','Dealership page · Contact','Section label','VISIT & CONTACT','VISITE & CONTACT','text',600),
('dealerPage.visitTitle','Dealership page · Contact','Section title','Lubumbashi showroom information.','Informations du showroom de Lubumbashi.','text',610),
('dealerPage.visitCopy','Dealership page · Contact','Section description','The dealership city is confirmed as Lubumbashi. The street address, telephone, WhatsApp number and opening hours are intentionally left unpublished until you provide the exact dealer details.','La ville de la concession est confirmée : Lubumbashi. L’adresse, le téléphone, le numéro WhatsApp et les horaires restent volontairement non publiés jusqu’à ce que vous fournissiez les coordonnées exactes.','textarea',620),
('dealerPage.locationLabel','Dealership page · Contact','Location label','Location','Localisation','text',630),
('dealerPage.phoneLabel','Dealership page · Contact','Phone label','Phone / WhatsApp','Téléphone / WhatsApp','text',640),
('dealerPage.hoursLabel','Dealership page · Contact','Hours label','Opening hours','Horaires d’ouverture','text',650),
('dealerPage.pending','Dealership page · Contact','Pending value','Awaiting dealer confirmation','En attente de confirmation','text',660),
('dealerPage.noFake','Dealership page · Contact','Phone note','No placeholder number is published.','Aucun faux numéro n’est publié.','text',670),
('dealerPage.noFakeHours','Dealership page · Contact','Hours note','Hours will be added once confirmed.','Les horaires seront ajoutés après confirmation.','text',680),
('dealerPage.cityArea','Dealership page · Contact','Map / showroom caption','Dealer city · exact showroom pin pending','Ville de la concession · emplacement exact à confirmer','text',690),
('dealerPage.promise1Title','Dealership page · Promises','Promise 1 title','See the real motorcycle','Voir la vraie moto','text',700),
('dealerPage.promise1Copy','Dealership page · Promises','Promise 1 description','The catalogue is built to transition from presentation artwork to your actual dealer photography.','Le catalogue est conçu pour remplacer facilement les visuels de présentation par vos vraies photos de concession.','textarea',710),
('dealerPage.promise2Title','Dealership page · Promises','Promise 2 title','Confirm the exact variant','Confirmer la variante exacte','text',720),
('dealerPage.promise2Copy','Dealership page · Promises','Promise 2 description','Engine, colour and specification details are only published after the local model is verified.','Le moteur, la couleur et les caractéristiques ne sont publiés qu’après vérification du modèle local.','textarea',730),
('dealerPage.promise3Title','Dealership page · Promises','Promise 3 title','Buy locally','Acheter localement','text',740),
('dealerPage.promise3Copy','Dealership page · Promises','Promise 3 description','The site directs customers to the Huanghe Motors dealership serving Lubumbashi.','Le site dirige les clients vers la concession Huanghe Motors desservant Lubumbashi.','textarea',750),
('dealerPage.rangeKicker','Dealership page · Range','Section label','CURRENT WEBSITE RANGE','GAMME ACTUELLE DU SITE','text',800),
('dealerPage.rangeCopy','Dealership page · Range','Section description','Start with the two confirmed Lubumbashi ranges. More motorcycles can be added without rebuilding the website.','Commencez avec les deux gammes confirmées à Lubumbashi. D’autres motos peuvent être ajoutées sans reconstruire le site.','textarea',810)
ON CONFLICT(key) DO NOTHING;
